//@ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as actualizacion$0 from "../../../../../piztu/internal/actualizacion/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as tao$0 from "../../../../../piztu/internal/tao/models.js";

function configure() {
    Object.freeze(Object.assign($Create.Events, {
        "actualizacion_piztu_cambiada": $$createType0,
        "ansible_setup_completo": $$createType1,
        "ansible_setup_log": $$createType1,
        "clave_completo": $$createType1,
        "clave_hosts_completo": $$createType1,
        "clave_hosts_log": $$createType1,
        "clave_log": $$createType1,
        "comando_completo": $$createType1,
        "comando_resultado": $$createType1,
        "descubrimento_completo": $$createType1,
        "descubrimento_log": $$createType1,
        "envio_completo": $$createType1,
        "envio_individualizado_completo": $$createType1,
        "estado_tao": $$createType3,
        "modulos_cambiado": $$createType1,
        "motor_cambiado": $$createType1,
        "ping_estado": $$createType1,
        "progreso_envio": $$createType1,
        "progreso_envio_individualizado": $$createType1,
        "progreso_recollida": $$createType1,
        "publicacions_modulo": $$createType5,
        "recollida_completa": $$createType1,
        "ruido_actual": $$createType1,
        "ruido_notificacion": $$createType1,
        "salt_setup_completo": $$createType1,
        "salt_setup_log": $$createType1,
        "scan_completo": $$createType1,
        "scan_log": $$createType1,
        "ssh_closed": $$createType1,
        "ssh_data": $$createType1,
        "tao_clientes_completo": $$createType1,
        "tao_clientes_log": $$createType1,
    }));
}

// Private type creation functions
const $$createType0 = actualizacion$0.Estado.createFrom;
const $$createType1 = $Create.Map($Create.Any, $Create.Any);
const $$createType2 = tao$0.Sesion.createFrom;
const $$createType3 = $Create.Map($Create.Any, $$createType2);
const $$createType4 = $Create.Map($Create.Any, $Create.Any);
const $$createType5 = $Create.Map($Create.Any, $$createType4);

configure();
