// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import type { Events } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import type * as actualizacion$0 from "../../../../../piztu/internal/actualizacion/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import type * as tao$0 from "../../../../../piztu/internal/tao/models.js";

declare module "@wailsio/runtime" {
    namespace Events {
        interface CustomEvents {
            "actualizacion_piztu_cambiada": actualizacion$0.Estado;
            "ansible_setup_completo": { [_ in string]?: any };
            "ansible_setup_log": { [_ in string]?: any };
            "clave_completo": { [_ in string]?: any };
            "clave_hosts_completo": { [_ in string]?: any };
            "clave_hosts_log": { [_ in string]?: any };
            "clave_log": { [_ in string]?: any };
            "comando_completo": { [_ in string]?: any };
            "comando_resultado": { [_ in string]?: any };
            "descubrimento_completo": { [_ in string]?: any };
            "descubrimento_log": { [_ in string]?: any };
            "envio_completo": { [_ in string]?: any };
            "envio_individualizado_completo": { [_ in string]?: any };
            "estado_tao": { [_ in string]?: tao$0.Sesion };
            "modulos_cambiado": { [_ in string]?: any };
            "motor_cambiado": { [_ in string]?: any };
            "ping_estado": { [_ in string]?: any };
            "progreso_envio": { [_ in string]?: any };
            "progreso_envio_individualizado": { [_ in string]?: any };
            "progreso_recollida": { [_ in string]?: any };
            "publicacions_modulo": { [_ in string]?: { [_ in string]?: string } };
            "recollida_completa": { [_ in string]?: any };
            "ruido_actual": { [_ in string]?: any };
            "ruido_notificacion": { [_ in string]?: any };
            "salt_setup_completo": { [_ in string]?: any };
            "salt_setup_log": { [_ in string]?: any };
            "scan_completo": { [_ in string]?: any };
            "scan_log": { [_ in string]?: any };
            "ssh_closed": { [_ in string]?: any };
            "ssh_data": { [_ in string]?: any };
            "tao_clientes_completo": { [_ in string]?: any };
            "tao_clientes_log": { [_ in string]?: any };
        }
    }
}
