// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * App é o núcleo de Piztu: expón métodos chamables desde o frontend (bindings)
 * e emite eventos de runtime. Substitúe a app.py + blueprints/*.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as actualizacion$0 from "./internal/actualizacion/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as tao$0 from "./internal/tao/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * AbrirCartafolModulos ábreo no xestor de ficheiros do sistema.
 * @returns {$CancellablePromise<void>}
 */
export function AbrirCartafolModulos() {
    return $Call.ByID(2460886932);
}

/**
 * AbrirFicheiro abre un ficheiro recollido co xestor/aplicación por defecto
 * do sistema (← main.py:abrir_cartafol_equipo, que usaba QDesktopServices).
 * @param {string} host
 * @param {string} nome
 * @returns {$CancellablePromise<void>}
 */
export function AbrirFicheiro(host, nome) {
    return $Call.ByID(1755594752, host, nome);
}

/**
 * AbrirModulo lanza un módulo externo (unha aplicación independente). Tao ten o
 * seu propio método por compatibilidade e polas rutas de busca herdadas.
 * @param {string} id
 * @returns {$CancellablePromise<void>}
 */
export function AbrirModulo(id) {
    return $Call.ByID(1723077861, id);
}

/**
 * AbrirTao abre Tao (instalado polo Paso 7 opcional do instalador,
 * en BaseDir/tao/) coma un proceso independente (← abrir_tao de
 * main.py). Devolve erro se non está instalado, para que o frontend poida
 * avisar o profesor. O peche (ou non) de Piztu decídeo o frontend: por
 * defecto substitúe a Piztu (chama a Quit() despois), agás con Ctrl+clic.
 * @returns {$CancellablePromise<void>}
 */
export function AbrirTao() {
    return $Call.ByID(4267387617);
}

/**
 * AccionsModulos devolve as accións dos módulos activos que o MOTOR ACTUAL pode
 * executar. Unha acción que só trae, por exemplo, un .sls non se ofrece estando
 * en SSH: mellor non pintar o botón que pintalo e que falle ao premelo.
 * @returns {$CancellablePromise<$models.AccionInfo[]>}
 */
export function AccionsModulos() {
    return $Call.ByID(496499644).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * ActualizarModulo substitúe un módulo xa instalado pola última versión do
 * catálogo (← botón "Actualizar" en ⚙ Aula → Módulos). Non toca se está
 * activo ou non: iso persístese á parte (ver modulos.Actualizar).
 * @param {string} id
 * @returns {$CancellablePromise<void>}
 */
export function ActualizarModulo(id) {
    return $Call.ByID(715543125, id);
}

/**
 * AlumnadoPorEquipo devolve, para cada equipo cunha sesión de Tao activa agora
 * mesmo, o nome e apelidos completos do alumno que o está a usar. Un equipo sen
 * sesión viva (ninguén loggeado, ou sesión caducada — ver tao.Sesion.Vivo) non
 * aparece: non hai a quen individualizar o contido dese equipo.
 * @returns {$CancellablePromise<{ [_ in string]?: string }>}
 */
export function AlumnadoPorEquipo() {
    return $Call.ByID(1206026250).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * AplicarActualizacionPiztu descarga a última versión de Piztu, substitúe o
 * executable en execución e arrinca xa a nova copia (← botón "Actualizar" no
 * diálogo "Sobre Piztu"). O frontend é quen peche esta xanela despois (Quit(),
 * mesmo camiño ca "Sair") en canto isto devolva sen erro — así non queda un
 * intre con dúas copias de Piztu abertas á vez.
 * @returns {$CancellablePromise<void>}
 */
export function AplicarActualizacionPiztu() {
    return $Call.ByID(3774644524);
}

/**
 * ComprobarActualizacionsModulos volve consultar o catálogo (piztu.org e
 * calquera github_repo do catálogo local) sen ter que reiniciar piztu (←
 * botón "🔄 Comprobar actualizacións" en ⚙ Aula → Módulos). Bloquea uns
 * segundos (ata timeoutIndice por chamada de rede) — o frontend desactiva o
 * botón mentres tanto; o repintado chega igual co evento modulos_cambiado.
 * @returns {$CancellablePromise<void>}
 */
export function ComprobarActualizacionsModulos() {
    return $Call.ByID(906106851);
}

/**
 * ComprobarSalt executa o diagnóstico do motor Salt e devolve a lista de
 * comprobacións para pintar en ⚙ Aula. Non modifica nada nin pide contrasinal:
 * é a resposta a "non me funciona e descoñezo o motivo", que ata agora só se
 * podía responder executando ordes de `salt` á man nunha terminal.
 * Devolve liñas xa formatadas, non as Comprobacion en cru, para que o binding
 * non teña que arrastrar un tipo novo ata o frontend: a estrutura (e as súas
 * probas) queda en saltsetup.Diagnostico, que é onde importa.
 * @returns {$CancellablePromise<string[]>}
 */
export function ComprobarSalt() {
    return $Call.ByID(3241176382).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * DescubrirRede escanea a rede local (porto 22, sen depender do inventario)
 * e devolve os equipos atopados por eventos "descubrimento_log" (progreso) e
 * "descubrimento_completo" (lista final). É a alternativa ao esquema
 * prefixo+número: atopa máquinas aínda non rexistradas na aula.
 * @returns {$CancellablePromise<void>}
 */
export function DescubrirRede() {
    return $Call.ByID(3116603374);
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function DetenerRuido() {
    return $Call.ByID(2714485879);
}

/**
 * DistribuirClaveHosts empurra a clave SSH compartida da aula a equipos
 * atopados por DescubrirRede, cada un co seu propio usuario/contrasinal (o
 * contrasinal só se usa unha vez, para esta distribución puntual). Os
 * equipos nos que ten éxito engádense ao inventario. Emite progreso por
 * "clave_hosts_log"/"clave_hosts_completo".
 * @param {$models.HostCredencial[]} credenciais
 * @returns {$CancellablePromise<void>}
 */
export function DistribuirClaveHosts(credenciais) {
    return $Call.ByID(926426476, credenciais);
}

/**
 * DistribuirClaveSSH xera (se cómpre) a clave compartida da aula e empúrraa a
 * todos os equipos do inventario por SSH nativo (sen sshpass). Emite progreso
 * polos eventos "clave_log" e "clave_completo". É o Paso "clave SSH" do
 * instalador, agora integrado en piztu e válido tamén en macOS.
 * @param {string} usuario
 * @param {string} contrasinal
 * @returns {$CancellablePromise<void>}
 */
export function DistribuirClaveSSH(usuario, contrasinal) {
    return $Call.ByID(3929742457, usuario, contrasinal);
}

/**
 * EnviarIndividualizado envía, a cada equipo, o ficheiro local que lle corresponde
 * (porEquipo: nome de equipo → ruta dun ficheiro xa existente nesta máquina). A
 * correspondencia equipo→ficheiro xa a decidiu quen chama (tipicamente cruzando
 * AlumnadoPorEquipo() co seu propio mapa alumno→ficheiro antes de chamar isto).
 * 
 * Devolve op_id de seguido; progreso e resultado final chegan por evento — mesmo
 * contrato de eventos que EnviarPracticas, en versión "individualizado":
 *   - "progreso_envio_individualizado": {op_id, host, estado: enviando|ok|erro, actual, total, msg}
 *   - "envio_individualizado_completo": {op_id, total, ok, erros}
 * @param {{ [_ in string]?: string }} porEquipo
 * @returns {$CancellablePromise<string>}
 */
export function EnviarIndividualizado(porEquipo) {
    return $Call.ByID(954264482, porEquipo);
}

/**
 * EnviarPracticas envía os ficheiros aos destinos. Devolve op_id. (← ficheiros.enviar_practicas)
 * @param {string[]} rutas
 * @param {string[]} destinos
 * @returns {$CancellablePromise<string>}
 */
export function EnviarPracticas(rutas, destinos) {
    return $Call.ByID(1028907050, rutas, destinos);
}

/**
 * EscanearRede conéctase por SSH (con clave) a cada equipo do inventario,
 * detecta os acendidos e garda a súa MAC no ficheiro `hosts` (para poder
 * acendelos por Wake-on-LAN). Emite progreso por "scan_log"/"scan_completo".
 * Porte nativo de xerarInventario.yaml, integrado en piztu.
 * @returns {$CancellablePromise<void>}
 */
export function EscanearRede() {
    return $Call.ByID(2668380809);
}

/**
 * ExecutarBloqueo bloquea `target` cos elementos marcados na configuración
 * gardada (← clic simple sobre "Bloquear", ou o botón LOK dun equipo). Mesmo
 * patrón de eventos ca ExecutarComando, con accion="bloqueoTotal" fixo para
 * que o frontend poida tratalo coma calquera outro resultado de comando.
 * @param {string} target
 * @returns {$CancellablePromise<void>}
 */
export function ExecutarBloqueo(target) {
    return $Call.ByID(3979644315, target);
}

/**
 * @param {string} accion
 * @param {string} target
 * @returns {$CancellablePromise<void>}
 */
export function ExecutarComando(accion, target) {
    return $Call.ByID(1322067457, accion, target);
}

/**
 * GardarCampoModulo persiste o valor dun campo do panel.
 * @param {string} moduloID
 * @param {string} campoID
 * @param {string} valor
 * @returns {$CancellablePromise<void>}
 */
export function GardarCampoModulo(moduloID, campoID, valor) {
    return $Call.ByID(4064624416, moduloID, campoID, valor);
}

/**
 * GardarLayout persiste a posición dun equipo (← /gardar_layout).
 * @param {string} nome
 * @param {number} x
 * @param {number} y
 * @returns {$CancellablePromise<void>}
 */
export function GardarLayout(nome, x, y) {
    return $Call.ByID(3386058922, nome, x, y);
}

/**
 * GardarOpcionsBloqueo persiste a configuración escollida na pantalla de
 * opcións (premido 3s sobre "Bloquear").
 * @param {{ [_ in string]?: boolean }} opcions
 * @returns {$CancellablePromise<void>}
 */
export function GardarOpcionsBloqueo(opcions) {
    return $Call.ByID(1830214348, opcions);
}

/**
 * @param {number} v
 * @returns {$CancellablePromise<void>}
 */
export function GardarUmbral(v) {
    return $Call.ByID(1830344883, v);
}

/**
 * GetActualizacionPiztu devolve a última foto de se hai actualización de
 * Piztu dispoñible, sen tocar a rede (← diálogo "Sobre Piztu" ao abrirse).
 * @returns {$CancellablePromise<actualizacion$0.Estado>}
 */
export function GetActualizacionPiztu() {
    return $Call.ByID(1176469992).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType4($result);
    }));
}

/**
 * GetAulaConfig devolve os datos da aula gardados, con valores por defecto
 * razoables a primeira vez (aula baleira aínda sen configurar).
 * @returns {$CancellablePromise<$models.AulaConfig>}
 */
export function GetAulaConfig() {
    return $Call.ByID(2861853712).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType5($result);
    }));
}

/**
 * GetEquipos devolve os equipos co seu nome e posición (← app.py:index).
 * @returns {$CancellablePromise<$models.Equipo[]>}
 */
export function GetEquipos() {
    return $Call.ByID(380500691).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType7($result);
    }));
}

/**
 * GetEstadoTao devolve o estado actual das sesións de Tao
 * (← GET /estado_tao), para a carga inicial do mapa antes do primeiro
 * evento periódico.
 * @returns {$CancellablePromise<{ [_ in string]?: tao$0.Sesion }>}
 */
export function GetEstadoTao() {
    return $Call.ByID(3600699887).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType9($result);
    }));
}

/**
 * @returns {$CancellablePromise<string>}
 */
export function GetMotor() {
    return $Call.ByID(3982671868);
}

/**
 * GetOpcionsBloqueo devolve que se bloquea por defecto (claves "internet",
 * "ssh", "son", "rato", "teclado"). Lémbrase entre sesións (bloqueo_opcions.json).
 * @returns {$CancellablePromise<{ [_ in string]?: boolean }>}
 */
export function GetOpcionsBloqueo() {
    return $Call.ByID(450801743).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType10($result);
    }));
}

/**
 * GetPublicacions devolve a foto actual das publicacións dos módulos, para a
 * carga inicial do mapa antes do primeiro evento periódico (mesmo patrón ca
 * GetEstadoTao).
 * @returns {$CancellablePromise<{ [_ in string]?: { [_ in string]?: string } }>}
 */
export function GetPublicacions() {
    return $Call.ByID(290261777).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType11($result);
    }));
}

/**
 * @returns {$CancellablePromise<number>}
 */
export function GetUmbral() {
    return $Call.ByID(1542906716);
}

/**
 * @returns {$CancellablePromise<string>}
 */
export function Idioma() {
    return $Call.ByID(3784485214);
}

/**
 * IdiomasDisponibles é a lista pechada de idiomas con ficheiro .lang propio
 * (recursos/idiomas/) — a mesma tríade de códigos (gl/es/en/pt) que xa usan
 * Tao, Xesta e Pancho, para que un módulo lanzado herde sempre un idioma que
 * tamén el sabe amosar (ver ContextoModulo.Idioma, escribirContexto).
 * @returns {$CancellablePromise<$models.IdiomaInfo[]>}
 */
export function IdiomasDisponibles() {
    return $Call.ByID(1592057939).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType13($result);
    }));
}

/**
 * IniciarRuido/DetenerRuido expóñense ao frontend, ligados á casilla "Activo"
 * (← chk_ruido/toggle_monitor de main.py).
 * IniciarRuido ARMA o control de ruído: a partir de aquí o monitor pode abrir
 * avisos e bloquear/desbloquear a aula el só. É o único camiño que arma, e
 * chámase desde un único sitio: manter premida 3s a icona do micrófono
 * (main.js). Non o chames desde ningún arranque automático.
 * @returns {$CancellablePromise<void>}
 */
export function IniciarRuido() {
    return $Call.ByID(2371931059);
}

/**
 * InstalarAnsible instala o motor Ansible. En Linux (Debian) instala o
 * paquete `ansible` con apt neste equipo, co mesmo contrasinal de sudo que
 * "Instalar Salt". En macOS instálao con Homebrew (se falta Homebrew, ábreo
 * nun Terminal para completar a instalación interactivamente). Emite
 * progreso por "ansible_setup_log"/"ansible_setup_completo".
 * @param {string} contrasinal
 * @returns {$CancellablePromise<void>}
 */
export function InstalarAnsible(contrasinal) {
    return $Call.ByID(1600105117, contrasinal);
}

/**
 * InstalarModulo descarga e descomprime un módulo do catálogo de piztu.org en
 * ModulosDir/<id>. Non o activa — iso queda para SetModulo, decisión do
 * profesor unha vez instalado (← botón "Descargar" en ⚙ Aula → Módulos).
 * @param {string} id
 * @returns {$CancellablePromise<void>}
 */
export function InstalarModulo(id) {
    return $Call.ByID(3418120913, id);
}

/**
 * InstalarSalt pon a punto Salt para a aula: (A) salt-master neste equipo (só
 * Linux; en macOS omítese), (B) salt-minion en cada cliente por SSH con clave,
 * e (C) aceptación das chaves no master. Emite progreso por "salt_setup_log" e
 * "salt_setup_completo". É o Paso 5 do instalador, integrado en piztu.
 * @param {string} masterAddr
 * @param {string} usuario
 * @param {string} contrasinal
 * @returns {$CancellablePromise<void>}
 */
export function InstalarSalt(masterAddr, usuario, contrasinal) {
    return $Call.ByID(3012247311, masterAddr, usuario, contrasinal);
}

/**
 * InstalarTaoClientes despraza Tao (o mesmo binario que xa usa AbrirTao no
 * servidor) a /opt/piztu en cada equipo cliente da aula, con acceso directo
 * no menú e no escritorio do alumnado. É a mesma acción que o instalador fai
 * unha soa vez (Paso 8), dispoñible aquí para repetila cando faga falla
 * (equipos novos, reinstalacións) sen volver pasar polo instalador.
 * @returns {$CancellablePromise<void>}
 */
export function InstalarTaoClientes() {
    return $Call.ByID(2945413334);
}

/**
 * LimparPracticas borra as prácticas nos destinos. Devolve op_id.
 * @param {string[]} destinos
 * @returns {$CancellablePromise<string>}
 */
export function LimparPracticas(destinos) {
    return $Call.ByID(1128954998, destinos);
}

/**
 * @param {string} host
 * @returns {$CancellablePromise<{ [_ in string]?: any }>}
 */
export function ListarFicheiros(host) {
    return $Call.ByID(3269305554, host).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType14($result);
    }));
}

/**
 * ModulosDispo devolve todos os módulos co seu estado, para a lista de caselas
 * da ventá ⚙ Aula. Mesmo patrón ca MotoresDispo().
 * @returns {$CancellablePromise<$models.ModuloInfo[]>}
 */
export function ModulosDispo() {
    return $Call.ByID(1629645069).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType16($result);
    }));
}

/**
 * MotorBase devolve o motor "base" deste sistema (o defecto por-OS: nativo en
 * macOS, salt en Linux). O frontend úsao para saber a que motor volver cando se
 * desactiva Ansible.
 * @returns {$CancellablePromise<string>}
 */
export function MotorBase() {
    return $Call.ByID(3139425079);
}

/**
 * MotoresDispo devolve os motores que teñen sentido neste sistema, co seu
 * estado, para que o menú poida amosar en gris os que non se poden usar agora
 * mesmo e explicar por que.
 * @returns {$CancellablePromise<$models.MotorInfo[]>}
 */
export function MotoresDispo() {
    return $Call.ByID(660477615).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType18($result);
    }));
}

/**
 * @param {string} id
 * @returns {$CancellablePromise<$models.PanelResposta | null>}
 */
export function PanelModulo(id) {
    return $Call.ByID(19474263, id).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType20($result);
    }));
}

/**
 * RecollerPracticas recolle os traballos dos destinos. Devolve op_id.
 * @param {string[]} destinos
 * @returns {$CancellablePromise<string>}
 */
export function RecollerPracticas(destinos) {
    return $Call.ByID(3473008485, destinos);
}

/**
 * RuidoArmado di se o control de ruído está armado agora mesmo. O frontend
 * consúltao ao arrincar para pintar a icona do micrófono conforme ao estado
 * real do backend: antes a icona nacía sempre apagada aínda que o monitor
 * estivese a traballar, e era imposible saber desde a aula que estaba activo.
 * @returns {$CancellablePromise<boolean>}
 */
export function RuidoArmado() {
    return $Call.ByID(3817091198);
}

/**
 * RutaModulos devolve o cartafol onde se engaden módulos novos, para amosalo na
 * ventá de configuración: en macOS está dentro de ~/Library, que Finder oculta
 * por defecto, así que hai que dicir onde é.
 * @returns {$CancellablePromise<string>}
 */
export function RutaModulos() {
    return $Call.ByID(3247004430);
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function SSHClose() {
    return $Call.ByID(462607351);
}

/**
 * @param {string} data
 * @returns {$CancellablePromise<void>}
 */
export function SSHInput(data) {
    return $Call.ByID(3709299103, data);
}

/**
 * @param {string} host
 * @returns {$CancellablePromise<void>}
 */
export function SSHOpen(host) {
    return $Call.ByID(2054696133, host);
}

/**
 * @param {number} cols
 * @param {number} rows
 * @returns {$CancellablePromise<void>}
 */
export function SSHResize(cols, rows) {
    return $Call.ByID(727969621, cols, rows);
}

/**
 * SelectFicheiros abre o diálogo nativo e devolve as rutas escollidas.
 * @returns {$CancellablePromise<string[]>}
 */
export function SelectFicheiros() {
    return $Call.ByID(2584716195).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * SetIdioma cambia o idioma activo de Piztu e persíste (internal/db, chave
 * "idioma") para que sobreviva a un reinicio — ver a lectura equivalente en
 * startup(). Devolve xa as traducións completas do idioma novo, para que o
 * frontend non teña que facer unha segunda chamada a Traducions().
 * 
 * Tao, Pancho e Xesta (xanela propia, proceso novo por lanzamento — ver
 * AbrirModulo) non reciben este cambio en quente se xa están abertos: só
 * lanzamentos futuros herdan o idioma novo coma valor por defecto (ver
 * ContextoModulo.Idioma) — cada un mantén a súa propia elección explícita se
 * xa a fixo.
 * @param {string} code
 * @returns {$CancellablePromise<{ [_ in string]?: string }>}
 */
export function SetIdioma(code) {
    return $Call.ByID(1328250320, code).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * SetModulo acende ou apaga un módulo e aplica o efecto no acto (arrancar ou
 * deter os seus monitores), para non obrigar a reiniciar piztu.
 * @param {string} id
 * @param {boolean} activo
 * @returns {$CancellablePromise<void>}
 */
export function SetModulo(id, activo) {
    return $Call.ByID(1643138981, id, activo);
}

/**
 * @param {string} nome
 * @returns {$CancellablePromise<string>}
 */
export function SetMotor(nome) {
    return $Call.ByID(3914699472, nome);
}

/**
 * Traducions expón as cadeas do idioma activo ao frontend (substitúe o Jinja t()).
 * @returns {$CancellablePromise<{ [_ in string]?: string }>}
 */
export function Traducions() {
    return $Call.ByID(3370696737).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * XerarInventario escribe o ficheiro `hosts` a partir dos datos da aula
 * (prefixo, dominio e número de equipos), persiste eses datos e devolve a ruta
 * escrita. É o primeiro paso da "Configuración" integrada: substitúe o que antes
 * facía o instalador, para que o profesor xere a aula desde o propio piztu
 * (tamén en macOS).
 * @param {string} prefixo
 * @param {string} dominio
 * @param {number} n
 * @returns {$CancellablePromise<string>}
 */
export function XerarInventario(prefixo, dominio, n) {
    return $Call.ByID(2963457064, prefixo, dominio, n);
}

// Private type creation functions
const $$createType0 = $models.AccionInfo.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = $Create.Map($Create.Any, $Create.Any);
const $$createType3 = $Create.Array($Create.Any);
const $$createType4 = actualizacion$0.Estado.createFrom;
const $$createType5 = $models.AulaConfig.createFrom;
const $$createType6 = $models.Equipo.createFrom;
const $$createType7 = $Create.Array($$createType6);
const $$createType8 = tao$0.Sesion.createFrom;
const $$createType9 = $Create.Map($Create.Any, $$createType8);
const $$createType10 = $Create.Map($Create.Any, $Create.Any);
const $$createType11 = $Create.Map($Create.Any, $$createType2);
const $$createType12 = $models.IdiomaInfo.createFrom;
const $$createType13 = $Create.Array($$createType12);
const $$createType14 = $Create.Map($Create.Any, $Create.Any);
const $$createType15 = $models.ModuloInfo.createFrom;
const $$createType16 = $Create.Array($$createType15);
const $$createType17 = $models.MotorInfo.createFrom;
const $$createType18 = $Create.Array($$createType17);
const $$createType19 = $models.PanelResposta.createFrom;
const $$createType20 = $Create.Nullable($$createType19);
