// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as modulos$0 from "./internal/modulos/models.js";

/**
 * AccionInfo é unha acción que trae un módulo, para pintar o seu botón.
 */
export class AccionInfo {
    /**
     * Creates a new AccionInfo instance.
     * @param {Partial<AccionInfo>} [$$source = {}] - The source object to create the AccionInfo.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("modulo" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["modulo"] = "";
        }
        if (!("etiqueta" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["etiqueta"] = "";
        }
        if (!("icona" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["icona"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AccionInfo instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {AccionInfo}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new AccionInfo(/** @type {Partial<AccionInfo>} */($$parsedSource));
    }
}

/**
 * AulaConfig son os datos da aula que persisten entre sesións (na táboa `axuste`).
 */
export class AulaConfig {
    /**
     * Creates a new AulaConfig instance.
     * @param {Partial<AulaConfig>} [$$source = {}] - The source object to create the AulaConfig.
     */
    constructor($$source = {}) {
        if (!("prefixo" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["prefixo"] = "";
        }
        if (!("dominio" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["dominio"] = "";
        }
        if (!("nequipos" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["nequipos"] = 0;
        }
        if (!("sshuser" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["sshuser"] = "";
        }
        if (!("saltmaster" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["saltmaster"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AulaConfig instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {AulaConfig}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new AulaConfig(/** @type {Partial<AulaConfig>} */($$parsedSource));
    }
}

/**
 * Equipo é un equipo do mapa coa súa posición.
 */
export class Equipo {
    /**
     * Creates a new Equipo instance.
     * @param {Partial<Equipo>} [$$source = {}] - The source object to create the Equipo.
     */
    constructor($$source = {}) {
        if (!("nome" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["nome"] = "";
        }
        if (!("x" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["x"] = 0;
        }
        if (!("y" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["y"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Equipo instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Equipo}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Equipo(/** @type {Partial<Equipo>} */($$parsedSource));
    }
}

/**
 * HostCredencial é un equipo descuberto por DescubrirRede xunto co
 * usuario/contrasinal que o admin escribiu para el (poden ser calquera,
 * non seguen a convención da aula).
 */
export class HostCredencial {
    /**
     * Creates a new HostCredencial instance.
     * @param {Partial<HostCredencial>} [$$source = {}] - The source object to create the HostCredencial.
     */
    constructor($$source = {}) {
        if (!("ip" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["ip"] = "";
        }
        if (!("usuario" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["usuario"] = "";
        }
        if (!("contrasinal" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["contrasinal"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new HostCredencial instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {HostCredencial}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new HostCredencial(/** @type {Partial<HostCredencial>} */($$parsedSource));
    }
}

/**
 * IdiomaInfo é un idioma dispoñible para o selector de ⚙ Configuración.
 */
export class IdiomaInfo {
    /**
     * Creates a new IdiomaInfo instance.
     * @param {Partial<IdiomaInfo>} [$$source = {}] - The source object to create the IdiomaInfo.
     */
    constructor($$source = {}) {
        if (!("code" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["code"] = "";
        }
        if (!("nome" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["nome"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new IdiomaInfo instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {IdiomaInfo}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new IdiomaInfo(/** @type {Partial<IdiomaInfo>} */($$parsedSource));
    }
}

/**
 * ModuloInfo describe un módulo para a ventá de configuración.
 */
export class ModuloInfo {
    /**
     * Creates a new ModuloInfo instance.
     * @param {Partial<ModuloInfo>} [$$source = {}] - The source object to create the ModuloInfo.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("clave" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["clave"] = "";
        }
        if (!("nome" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["nome"] = "";
        }
        if (!("icona" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["icona"] = "";
        }
        if (!("iconaImaxeDataURI" in $$source)) {
            /**
             * IconaImaxeDataURI, cando non baleiro, substitúe Icona por unha imaxe
             * (ver modulos.Modulo.IconaImaxeDataURI) nos botóns do frontend.
             * @member
             * @type {string}
             */
            this["iconaImaxeDataURI"] = "";
        }
        if (!("activo" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["activo"] = false;
        }
        if (!("interno" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["interno"] = false;
        }
        if (!("dispo" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["dispo"] = false;
        }
        if (!("motivo" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["motivo"] = "";
        }
        if (!("instalado" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["instalado"] = false;
        }
        if (!("novo" in $$source)) {
            /**
             * Novo marca un módulo que aínda non se activou nin desactivou nunca: é o
             * que acaba de aparecer no cartafol e agarda decisión.
             * @member
             * @type {boolean}
             */
            this["novo"] = false;
        }
        if (!("ten_panel" in $$source)) {
            /**
             * TenPanel indica que o módulo trae unha pantalla de configuración propia.
             * @member
             * @type {boolean}
             */
            this["ten_panel"] = false;
        }
        if (!("ruta" in $$source)) {
            /**
             * Ruta é onde vive o ficheiro do módulo, ou "" se non ten ningún porque vai
             * dentro de piztu. Amósase na lista para que se entenda de vista para que
             * serve o cartafol de módulos e que hai (ou non) dentro.
             * @member
             * @type {string}
             */
            this["ruta"] = "";
        }
        if (!("descargable" in $$source)) {
            /**
             * Descargable indica que o módulo está no catálogo de piztu.org e pode
             * instalarse premendo "Descargar", en vez de copialo á man.
             * @member
             * @type {boolean}
             */
            this["descargable"] = false;
        }
        if (!("version" in $$source)) {
            /**
             * Version é a declarada no modulo.json instalado (baleira se o módulo non
             * a declara). VersionNova é a do catálogo cando é máis nova ca instalada
             * (ver modulos.VersionMaior) — só ten sentido xunto con Actualizable.
             * @member
             * @type {string}
             */
            this["version"] = "";
        }
        if (!("version_nova" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["version_nova"] = "";
        }
        if (!("actualizable" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["actualizable"] = false;
        }
        if (!("autor" in $$source)) {
            /**
             * Autor, Email e Web son metadatos informativos que o módulo declara no
             * seu modulo.json (opcionais).
             * @member
             * @type {string}
             */
            this["autor"] = "";
        }
        if (!("email" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["email"] = "";
        }
        if (!("web" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["web"] = "";
        }
        if (!("descricion" in $$source)) {
            /**
             * Descricion é o texto curto opcional que o módulo declara no seu
             * modulo.json, amosado xunto ao nome en ⚙ Aula → Módulos.
             * @member
             * @type {string}
             */
            this["descricion"] = "";
        }
        if (!("mantenPiztuAberto" in $$source)) {
            /**
             * MantenPiztuAberto — ver modulos.Modulo.MantenPiztuAberto. Lido polo
             * frontend para decidir se peche Piztu ao abrir este módulo (ver
             * pintarBotonsExternos en main.js).
             * @member
             * @type {boolean}
             */
            this["mantenPiztuAberto"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ModuloInfo instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ModuloInfo}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ModuloInfo(/** @type {Partial<ModuloInfo>} */($$parsedSource));
    }
}

/**
 * MotorInfo describe un motor para o menú do botón ⚙.
 */
export class MotorInfo {
    /**
     * Creates a new MotorInfo instance.
     * @param {Partial<MotorInfo>} [$$source = {}] - The source object to create the MotorInfo.
     */
    constructor($$source = {}) {
        if (!("nome" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["nome"] = "";
        }
        if (!("etiqueta" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["etiqueta"] = "";
        }
        if (!("dispo" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["dispo"] = false;
        }
        if (!("motivo" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["motivo"] = "";
        }
        if (!("recomendar" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["recomendar"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new MotorInfo instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {MotorInfo}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new MotorInfo(/** @type {Partial<MotorInfo>} */($$parsedSource));
    }
}

/**
 * PanelModulo devolve a descrición do panel dun módulo activo (ou nil).
 * Acompáñase dos valores xa gardados e dos equipos, para poder encher as listas
 * con `fonte: equipos` sen unha segunda chamada.
 */
export class PanelResposta {
    /**
     * Creates a new PanelResposta instance.
     * @param {Partial<PanelResposta>} [$$source = {}] - The source object to create the PanelResposta.
     */
    constructor($$source = {}) {
        if (!("panel" in $$source)) {
            /**
             * @member
             * @type {modulos$0.Panel | null}
             */
            this["panel"] = null;
        }
        if (!("valores" in $$source)) {
            /**
             * @member
             * @type {{ [_ in string]?: string }}
             */
            this["valores"] = {};
        }
        if (!("equipos" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["equipos"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PanelResposta instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {PanelResposta}
     */
    static createFrom($$source = {}) {
        const $$createField0_0 = $$createType1;
        const $$createField1_0 = $$createType2;
        const $$createField2_0 = $$createType3;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("panel" in $$parsedSource) {
            $$parsedSource["panel"] = $$createField0_0($$parsedSource["panel"]);
        }
        if ("valores" in $$parsedSource) {
            $$parsedSource["valores"] = $$createField1_0($$parsedSource["valores"]);
        }
        if ("equipos" in $$parsedSource) {
            $$parsedSource["equipos"] = $$createField2_0($$parsedSource["equipos"]);
        }
        return new PanelResposta(/** @type {Partial<PanelResposta>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = modulos$0.Panel.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = $Create.Map($Create.Any, $Create.Any);
const $$createType3 = $Create.Array($Create.Any);
