// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {actualizacion} from '../models';
import {tao} from '../models';

export function AbrirCartafolModulos():Promise<void>;

export function AbrirFicheiro(arg1:string,arg2:string):Promise<void>;

export function AbrirModulo(arg1:string):Promise<void>;

export function AbrirTao():Promise<void>;

export function AccionsModulos():Promise<Array<main.AccionInfo>>;

export function ActualizarModulo(arg1:string):Promise<void>;

export function AlumnadoPorEquipo():Promise<Record<string, string>>;

export function AplicarActualizacionPiztu():Promise<void>;

export function ComprobarActualizacionsModulos():Promise<void>;

export function DescubrirRede():Promise<void>;

export function DetenerRuido():Promise<void>;

export function DistribuirClaveHosts(arg1:Array<main.HostCredencial>):Promise<void>;

export function DistribuirClaveSSH(arg1:string,arg2:string):Promise<void>;

export function EnviarIndividualizado(arg1:Record<string, string>):Promise<string>;

export function EnviarPracticas(arg1:Array<string>,arg2:Array<string>):Promise<string>;

export function EscanearRede():Promise<void>;

export function ExecutarBloqueo(arg1:string):Promise<void>;

export function ExecutarComando(arg1:string,arg2:string):Promise<void>;

export function GardarCampoModulo(arg1:string,arg2:string,arg3:string):Promise<void>;

export function GardarLayout(arg1:string,arg2:number,arg3:number):Promise<void>;

export function GardarOpcionsBloqueo(arg1:Record<string, boolean>):Promise<void>;

export function GardarUmbral(arg1:number):Promise<void>;

export function GetActualizacionPiztu():Promise<actualizacion.Estado>;

export function GetAulaConfig():Promise<main.AulaConfig>;

export function GetEquipos():Promise<Array<main.Equipo>>;

export function GetEstadoTao():Promise<Record<string, tao.Sesion>>;

export function GetMotor():Promise<string>;

export function GetOpcionsBloqueo():Promise<Record<string, boolean>>;

export function GetPublicacions():Promise<Record<string, Record<string, string>>>;

export function GetUmbral():Promise<number>;

export function Idioma():Promise<string>;

export function IdiomasDisponibles():Promise<Array<main.IdiomaInfo>>;

export function IniciarRuido():Promise<void>;

export function InstalarAnsible(arg1:string):Promise<void>;

export function InstalarModulo(arg1:string):Promise<void>;

export function InstalarSalt(arg1:string,arg2:string,arg3:string):Promise<void>;

export function InstalarTaoClientes():Promise<void>;

export function LimparPracticas(arg1:Array<string>):Promise<string>;

export function ListarFicheiros(arg1:string):Promise<Record<string, any>>;

export function ModulosDispo():Promise<Array<main.ModuloInfo>>;

export function MotorBase():Promise<string>;

export function MotoresDispo():Promise<Array<main.MotorInfo>>;

export function PanelModulo(arg1:string):Promise<main.PanelResposta>;

export function RecollerPracticas(arg1:Array<string>):Promise<string>;

export function RutaModulos():Promise<string>;

export function SSHClose():Promise<void>;

export function SSHInput(arg1:string):Promise<void>;

export function SSHOpen(arg1:string):Promise<void>;

export function SSHResize(arg1:number,arg2:number):Promise<void>;

export function SelectFicheiros():Promise<Array<string>>;

export function SetIdioma(arg1:string):Promise<Record<string, string>>;

export function SetModulo(arg1:string,arg2:boolean):Promise<void>;

export function SetMotor(arg1:string):Promise<string>;

export function Traducions():Promise<Record<string, string>>;

export function XerarInventario(arg1:string,arg2:string,arg3:number):Promise<string>;
