// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AbrirCartafolModulos() {
  return window['go']['main']['App']['AbrirCartafolModulos']();
}

export function AbrirFicheiro(arg1, arg2) {
  return window['go']['main']['App']['AbrirFicheiro'](arg1, arg2);
}

export function AbrirModulo(arg1) {
  return window['go']['main']['App']['AbrirModulo'](arg1);
}

export function AbrirTao() {
  return window['go']['main']['App']['AbrirTao']();
}

export function AccionsModulos() {
  return window['go']['main']['App']['AccionsModulos']();
}

export function ActualizarModulo(arg1) {
  return window['go']['main']['App']['ActualizarModulo'](arg1);
}

export function AlumnadoPorEquipo() {
  return window['go']['main']['App']['AlumnadoPorEquipo']();
}

export function AplicarActualizacionPiztu() {
  return window['go']['main']['App']['AplicarActualizacionPiztu']();
}

export function ComprobarActualizacionsModulos() {
  return window['go']['main']['App']['ComprobarActualizacionsModulos']();
}

export function DescubrirRede() {
  return window['go']['main']['App']['DescubrirRede']();
}

export function DetenerRuido() {
  return window['go']['main']['App']['DetenerRuido']();
}

export function DistribuirClaveHosts(arg1) {
  return window['go']['main']['App']['DistribuirClaveHosts'](arg1);
}

export function DistribuirClaveSSH(arg1, arg2) {
  return window['go']['main']['App']['DistribuirClaveSSH'](arg1, arg2);
}

export function EnviarIndividualizado(arg1) {
  return window['go']['main']['App']['EnviarIndividualizado'](arg1);
}

export function EnviarPracticas(arg1, arg2) {
  return window['go']['main']['App']['EnviarPracticas'](arg1, arg2);
}

export function EscanearRede() {
  return window['go']['main']['App']['EscanearRede']();
}

export function ExecutarBloqueo(arg1) {
  return window['go']['main']['App']['ExecutarBloqueo'](arg1);
}

export function ExecutarComando(arg1, arg2) {
  return window['go']['main']['App']['ExecutarComando'](arg1, arg2);
}

export function GardarCampoModulo(arg1, arg2, arg3) {
  return window['go']['main']['App']['GardarCampoModulo'](arg1, arg2, arg3);
}

export function GardarLayout(arg1, arg2, arg3) {
  return window['go']['main']['App']['GardarLayout'](arg1, arg2, arg3);
}

export function GardarOpcionsBloqueo(arg1) {
  return window['go']['main']['App']['GardarOpcionsBloqueo'](arg1);
}

export function GardarUmbral(arg1) {
  return window['go']['main']['App']['GardarUmbral'](arg1);
}

export function GetActualizacionPiztu() {
  return window['go']['main']['App']['GetActualizacionPiztu']();
}

export function GetAulaConfig() {
  return window['go']['main']['App']['GetAulaConfig']();
}

export function GetEquipos() {
  return window['go']['main']['App']['GetEquipos']();
}

export function GetEstadoTao() {
  return window['go']['main']['App']['GetEstadoTao']();
}

export function GetMotor() {
  return window['go']['main']['App']['GetMotor']();
}

export function GetOpcionsBloqueo() {
  return window['go']['main']['App']['GetOpcionsBloqueo']();
}

export function GetPublicacions() {
  return window['go']['main']['App']['GetPublicacions']();
}

export function GetUmbral() {
  return window['go']['main']['App']['GetUmbral']();
}

export function Idioma() {
  return window['go']['main']['App']['Idioma']();
}

export function IdiomasDisponibles() {
  return window['go']['main']['App']['IdiomasDisponibles']();
}

export function IniciarRuido() {
  return window['go']['main']['App']['IniciarRuido']();
}

export function InstalarAnsible(arg1) {
  return window['go']['main']['App']['InstalarAnsible'](arg1);
}

export function InstalarModulo(arg1) {
  return window['go']['main']['App']['InstalarModulo'](arg1);
}

export function InstalarSalt(arg1, arg2, arg3) {
  return window['go']['main']['App']['InstalarSalt'](arg1, arg2, arg3);
}

export function InstalarTaoClientes() {
  return window['go']['main']['App']['InstalarTaoClientes']();
}

export function LimparPracticas(arg1) {
  return window['go']['main']['App']['LimparPracticas'](arg1);
}

export function ListarFicheiros(arg1) {
  return window['go']['main']['App']['ListarFicheiros'](arg1);
}

export function ModulosDispo() {
  return window['go']['main']['App']['ModulosDispo']();
}

export function MotorBase() {
  return window['go']['main']['App']['MotorBase']();
}

export function MotoresDispo() {
  return window['go']['main']['App']['MotoresDispo']();
}

export function PanelModulo(arg1) {
  return window['go']['main']['App']['PanelModulo'](arg1);
}

export function RecollerPracticas(arg1) {
  return window['go']['main']['App']['RecollerPracticas'](arg1);
}

export function RutaModulos() {
  return window['go']['main']['App']['RutaModulos']();
}

export function SSHClose() {
  return window['go']['main']['App']['SSHClose']();
}

export function SSHInput(arg1) {
  return window['go']['main']['App']['SSHInput'](arg1);
}

export function SSHOpen(arg1) {
  return window['go']['main']['App']['SSHOpen'](arg1);
}

export function SSHResize(arg1, arg2) {
  return window['go']['main']['App']['SSHResize'](arg1, arg2);
}

export function SelectFicheiros() {
  return window['go']['main']['App']['SelectFicheiros']();
}

export function SetIdioma(arg1) {
  return window['go']['main']['App']['SetIdioma'](arg1);
}

export function SetModulo(arg1, arg2) {
  return window['go']['main']['App']['SetModulo'](arg1, arg2);
}

export function SetMotor(arg1) {
  return window['go']['main']['App']['SetMotor'](arg1);
}

export function Traducions() {
  return window['go']['main']['App']['Traducions']();
}

export function XerarInventario(arg1, arg2, arg3) {
  return window['go']['main']['App']['XerarInventario'](arg1, arg2, arg3);
}
