// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * Estado é o resultado de comprobar unha actualización de Piztu.
 */
export class Estado {
    /**
     * Creates a new Estado instance.
     * @param {Partial<Estado>} [$$source = {}] - The source object to create the Estado.
     */
    constructor($$source = {}) {
        if (!("disponible" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["disponible"] = false;
        }
        if (!("version_local" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["version_local"] = "";
        }
        if (!("version_remota" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["version_remota"] = "";
        }
        if (!("url_descarga" in $$source)) {
            /**
             * "" se non hai asset .zip descargable
             * @member
             * @type {string}
             */
            this["url_descarga"] = "";
        }
        if (!("url_checksum" in $$source)) {
            /**
             * "" se a Release non publica "<zip>.sha256"
             * @member
             * @type {string}
             */
            this["url_checksum"] = "";
        }
        if (!("notas" in $$source)) {
            /**
             * descrición da Release (changelog)
             * @member
             * @type {string}
             */
            this["notas"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Estado instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Estado}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Estado(/** @type {Partial<Estado>} */($$parsedSource));
    }
}
