// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * Sesion é o estado dun equipo, tal e como o consome o frontend (mesmo
 * contrato JSON que /estado_tao en blueprints/tao.py). Ve tamén
 * dixitalizacion/filebrowser.go (sesionTao) no lado de quen escribe.
 */
export class Sesion {
    /**
     * Creates a new Sesion instance.
     * @param {Partial<Sesion>} [$$source = {}] - The source object to create the Sesion.
     */
    constructor($$source = {}) {
        if (!("usuario" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["usuario"] = "";
        }
        if (!("nome" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["nome"] = "";
        }
        if (!("grupo" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["grupo"] = "";
        }
        if (!("conectado" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["conectado"] = false;
        }
        if (!("actualizado" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["actualizado"] = "";
        }
        if (!("vivo" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["vivo"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Sesion instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Sesion}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Sesion(/** @type {Partial<Sesion>} */($$parsedSource));
    }
}
