// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * Campo é un control do panel.
 */
export class Campo {
    /**
     * Creates a new Campo instance.
     * @param {Partial<Campo>} [$$source = {}] - The source object to create the Campo.
     */
    constructor($$source = {}) {
        if (!("tipo" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["tipo"] = "";
        }
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("etiqueta" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["etiqueta"] = "";
        }
        if (!("axuda" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["axuda"] = "";
        }
        if (!("defecto" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["defecto"] = "";
        }
        if (!("opcions" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["opcions"] = [];
        }
        if (!("fonte" in $$source)) {
            /**
             * Fonte enche unha lista con datos de piztu en vez de con `opcions`.
             * Único valor admitido de momento: "equipos".
             * @member
             * @type {string}
             */
            this["fonte"] = "";
        }
        if (!("accion" in $$source)) {
            /**
             * Accion é o id da acción que dispara un botón (das que declara o módulo).
             * @member
             * @type {string}
             */
            this["accion"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Campo instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Campo}
     */
    static createFrom($$source = {}) {
        const $$createField5_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("opcions" in $$parsedSource) {
            $$parsedSource["opcions"] = $$createField5_0($$parsedSource["opcions"]);
        }
        return new Campo(/** @type {Partial<Campo>} */($$parsedSource));
    }
}

/**
 * Panel é a descrición completa da interface dun módulo.
 */
export class Panel {
    /**
     * Creates a new Panel instance.
     * @param {Partial<Panel>} [$$source = {}] - The source object to create the Panel.
     */
    constructor($$source = {}) {
        if (!("titulo" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["titulo"] = "";
        }
        if (!("campos" in $$source)) {
            /**
             * @member
             * @type {Campo[]}
             */
            this["campos"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Panel instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Panel}
     */
    static createFrom($$source = {}) {
        const $$createField1_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("campos" in $$parsedSource) {
            $$parsedSource["campos"] = $$createField1_0($$parsedSource["campos"]);
        }
        return new Panel(/** @type {Partial<Panel>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
const $$createType1 = Campo.createFrom;
const $$createType2 = $Create.Array($$createType1);
